name: Deploy to Production
on:
  pull_request:
    types: [opened]

env:
  AUTHORS: '["Ansuman28", "iabukar"]'
  BRANCH: main
  SERVICES_DIR: services
  SERVERLESS_DIR: serverless
  AKS-ACR: crqprodaksacr
  NODE_V18: '18'
  NODE_V20: '20'

jobs:

  pre-checks:
    name: Check Release Tagging
    runs-on: [self-hosted, pcoe-runner-linux-small-prod]

    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Tag Presence In Branch
        id: check-branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "VALID_BRANCH=$branch" >> $GITHUB_ENV

      - name: Check Tag & Actor
        id: check-tag-actor
        run: |
          echo "Actor: ${{ github.actor }}, Tag: ${{ github.ref }}, Branch: ${{ env.VALID_BRANCH }}"

      - name: Save Check Status
        run: |
          echo "IS_VALID=${{ contains(fromJSON(env.AUTHORS),github.actor) && env.VALID_BRANCH==env.BRANCH }}" >> $GITHUB_ENV

    outputs:
      validated: ${{ env.IS_VALID }}

  display-valid:
    name: Display Valid
    runs-on: [self-hosted, pcoe-runner-linux-small-prod]

    steps:
      - name: Display Valid
        run: echo ${{ env.IS_VALID }}
        
      - name: codeowner
        id: codeowner
        uses: SvanBoxel/codeowners-action@v1
        with: 
          path: './.github/CODEOWNERS'

      - name: Display CODEOWNERS
        run: echo ${{ steps.codeowners.outputs.codeowners }}
